Repository LukeHackett/vite-plugin-build-info-file, pull requests merged in 2025-01, with the labels that each got.

#1 Addition of project documentation
  .github/docs/logo.png
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: documentation

#2 Setup plugin boilerplate
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .husky/pre-commit
  package-lock.json
  package.json
  src/index.test.ts
  src/index.ts
  src/plugin.test.ts
  src/plugin.ts
  src/types.ts
Labels: enhancement

#3 Addition of the Plugin implementation
  README.md
  package-lock.json
  package.json
  src/contributors/git.test.ts
  src/contributors/git.ts
  src/contributors/index.ts
  src/contributors/node.test.ts
  src/contributors/node.ts
  src/contributors/package.test.ts
  src/contributors/package.ts
  src/contributors/platform.test.ts
  src/contributors/platform.ts
  src/index.ts
  src/info.test.ts
  src/info.ts
  src/plugin.test.ts
  src/plugin.ts
  src/types.ts
  tsup.config.ts
Labels: enhancement

#5 Fixes to configuration defaults
  .gitignore
  src/contributors/git.test.ts
  src/contributors/git.ts
  src/plugin.test.ts
  src/plugin.ts
  src/types.ts
Labels: enhancement

#6 Adding support for the info property within plugin config
  src/info.test.ts
  src/info.ts
Labels: enhancement

#7 Merge options with the default config
  package-lock.json
  package.json
  src/plugin.test.ts
  src/plugin.ts
Labels: bug

#8 Adding info.json file example into README.md
  README.md
Labels: documentation

#9 Adding support for vite dev server
  package-lock.json
  package.json
  src/info.test.ts
  src/info.ts
  src/plugin.test.ts
  src/plugin.ts
Labels: enhancement
